-- Tabla para Control de Turnos (Asistencia)
CREATE TABLE public.work_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) NOT NULL,
  rol TEXT NOT NULL, -- Snapshot del rol al momento de iniciar (por si cambia después)
  started_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  ended_at TIMESTAMP WITH TIME ZONE,
  status TEXT DEFAULT 'activo' CHECK (status IN ('activo', 'finalizado')),
  
  -- Métricas de cierre (opcional, para guardar resumen)
  metrics JSONB DEFAULT '{}'::jsonb,
  
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Indices
CREATE INDEX idx_work_sessions_user ON public.work_sessions(user_id);
CREATE INDEX idx_work_sessions_status ON public.work_sessions(status);
CREATE INDEX idx_work_sessions_date ON public.work_sessions(started_at);

-- Realtime
alter publication supabase_realtime add table public.work_sessions;

-- RLS (Seguridad)
ALTER TABLE public.work_sessions ENABLE ROW LEVEL SECURITY;

-- Politicas
-- 1. Usuarios pueden ver sus propias sesiones
CREATE POLICY "Usuarios ven sus sesiones" ON public.work_sessions
FOR SELECT USING (auth.uid() = user_id);

-- 2. Admins pueden ver todas las sesiones
CREATE POLICY "Admins ven todo work_sessions" ON public.work_sessions
FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND rol = 'administrador')
);

-- 3. Usuarios pueden crear su propia sesión (Iniciar Turno)
CREATE POLICY "Usuarios crean su sesion" ON public.work_sessions
FOR INSERT WITH CHECK (auth.uid() = user_id);

-- 4. Usuarios pueden actualizar su propia sesión (Cerrar Turno)
CREATE POLICY "Usuarios cierran su sesion" ON public.work_sessions
FOR UPDATE USING (auth.uid() = user_id);
