-- Create table for waiter notifications
CREATE TABLE IF NOT EXISTS waiter_calls (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    mesa_id int references mesas(id), -- Optional
    sender_role text not null, -- 'cocina', 'bar', 'caja'
    recipient_waiter_id uuid references auth.users(id), -- Specific waiter
    sender_user_id uuid references auth.users(id), -- Who called
    message text,
    status text default 'pending' -- pending, resolved
);

-- Enable RLS
ALTER TABLE waiter_calls ENABLE ROW LEVEL SECURITY;

-- Policy: Everyone can insert
CREATE POLICY "Enable insert for authenticated users" ON waiter_calls FOR INSERT TO authenticated WITH CHECK (true);

-- Policy: Waiters can see their own calls (or broadcast calls)
CREATE POLICY "Waiters see their calls" ON waiter_calls FOR SELECT TO authenticated 
USING (
    recipient_waiter_id = auth.uid() OR 
    recipient_waiter_id IS NULL OR 
    sender_user_id = auth.uid()
);

-- Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE waiter_calls;
